name: "VirusTotal Action"
description: "Scan Files for Malware using the Virus Total API"
author: "Shane"
branding:
  icon: "shield"
  color: "blue"

inputs:
  github_token:
    description: "GitHub Token from secrets.GITHUB_TOKEN"
    required: true
  vt_api_key:
    description: "VirusTotal API Token from secrets"
    required: true
  file_globs:
    description: "File Globs to Process"
    required: false
  rate_limit:
    description: "Per Minute Rate Limit for API Calls"
    required: false
    default: "4"
  update_release:
    description: "Update Release Notes with VT Links"
    required: false
    default: "true"

outputs:
  results:
    description: "Generated Docker tags"

runs:
  using: "node20"
  main: "dist/index.js"
