name: "VirusTotal Action"
description: "Scan Files for Malware using the Virus Total API"
author: "Shane"
branding:
  icon: "shield"
  color: "blue"

inputs:
  vt_api_key:
    description: "VirusTotal API Key"
    required: true
  file_globs:
    description: "File Globs to Process"
    required: false
  rate_limit:
    description: "API Calls Per Minute"
    required: false
    default: "4"
  update_release:
    description: "Update Release Notes"
    required: false
    default: "true"
  release_heading:
    description: "Release Notes Heading"
    required: false
    default: "🛡️ **VirusTotal Results:**"
  collapsed:
    description: "Show Links Collapsed"
    required: false
    default: "false"
  summary:
    description: "Add Summary to Job"
    required: false
    default: "true"
  github_token:
    description: "Only for external or PAT"
    required: false
    default: ${{ github.token }}

outputs:
  results:
    description: "Comma Seperated String of file/id"
  json:
    description: "JSON Object List Results String"

runs:
  using: "node20"
  main: "dist/index.js"
