name: "Lint"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      pull-requests: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Setup Node 24"
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: "Install"
        id: install
        run: |
          npm ci

      - name: "ESLint"
        id: eslint
        if: ${{ !cancelled() }}
        run: |
          npm run lint:report

      - name: "Prettier"
        if: ${{ !cancelled() }}
        run: |
          npm run prettier:check

      - name: "Yamllint"
        if: ${{ !cancelled() }}
        env:
          CONFIG: "{extends: relaxed, ignore: [node_modules/], rules: {line-length: {max: 119}}}"
        run: |
          echo "::group::List Files"
          yamllint -d '${{ env.CONFIG }}' --list-files .
          echo "::endgroup::"
          yamllint -d '${{ env.CONFIG }}' .

      - name: "Actionlint"
        if: ${{ !cancelled() }}
        run: |
          echo "::group::Download"
          loc=$(curl -sI https://github.com/rhysd/actionlint/releases/latest | grep -i '^location:')
          echo "loc: ${loc}"
          tag=$(echo "${loc}" | sed -E 's|.*/tag/v?(.*)|\1|' | tr -d '\t\r\n')
          echo "tag: ${tag}"
          url="https://github.com/rhysd/actionlint/releases/latest/download/actionlint_${tag}_linux_amd64.tar.gz"
          echo "url: ${url}"
          curl -sL "${url}" | tar xz -C "${RUNNER_TEMP}" actionlint
          file "${RUNNER_TEMP}/actionlint"
          "${RUNNER_TEMP}/actionlint" --version
          echo "::endgroup::"
          "${RUNNER_TEMP}/actionlint" -color -verbose -shellcheck= -pyflakes=

      - name: "Verify action.yml"
        if: ${{ !cancelled() }}
        run: |
          yq -e '.runs.main | test("^dist/")' action.yml

      - name: "Check Build Action"
        if: ${{ !cancelled() }}
        uses: cssnr/check-build-action@v1

      - name: "ESLint Annotate"
        if: ${{ !cancelled() && steps.eslint.outcome != 'success' }}
        continue-on-error: true
        uses: ataylorme/eslint-annotate-action@v3
