name: "Pull"

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pull:
    name: "Pull"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      pull-requests: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "NPM Outdated Check"
        continue-on-error: true
        uses: cssnr/npm-outdated-action@master
